routers = [
    {
        "name": "R1",
        "device_type": "cisco_ios",
        "host": "192.168.54.136",
        "username": "admin",
        "password": "admin123",
        "secret": "admin123",
    },
    {
        "name": "R2",
        "device_type": "cisco_ios",
        "host": "192.168.54.137",
        "username": "admin",
        "password": "admin123",
        "secret": "admin123",
    },
    {
        "name": "R3",
        "host": "192.168.54.138",
        "device_type": "cisco_ios",
        "username": "admin",
        "password": "admin123",
        "secret": "admin123",
    },
    {
        "name": "R4",
        "host": "192.168.54.139",
        "device_type": "cisco_ios",
        "username": "admin",
        "password": "admin123",
        "secret": "admin123",
    },
    {
        "name": "R5",
        "host": "192.168.54.140",
        "device_type": "cisco_ios",
        "username": "admin",
        "password": "admin123",
        "secret": "admin123",
    },
    {
        "name": "R6",
        "host": "192.168.54.141",
        "device_type": "cisco_ios",
        "username": "admin",
        "password": "admin123",
        "secret": "admin123",
    },
]
